### ISSUE TITLE
Difference between iOS & Android

### ISSUE THREAD

**Issue by Sideral-Inc** [ionic-team/cordova-plugin-ionic-keyboard#10]
Hi,

I'm currently maintaining an Ionic v1 app and find out that the plugin is different from iOS & Android.

In the doc, it's written that there is a method called Keyboard.hideFormAccessoryBar.

It's true for iOS but on Android, the method is called Keyboard.hideKeyboardAccessoryBar.

Would be nice to update the documentation.

**Comment by TheDuc** [comment]
This is true, and the hideKeyboardAccessoryBar method does nothing on Android.
There is no "hideKeyboardAccessoryBar" action in the java source code.

**Comment by mlynch** [comment]
Recent merges fix this

**Comment by Sideral-Inc** [comment]
There is no 2.1.0 release in the Releases tab.
