### ISSUE TITLE
feat: add ability to change label on accessory bar

### ISSUE THREAD

**Issue by Livijn** [ionic-team/cordova-plugin-ionic-keyboard#100]
Right now, when displaying the accessory bar `Keyboard.setAccessoryBarVisible({isVisible: false});` you cannot change the "Done" label. 

This is an accessory bar:
![](https://www.oreilly.com/library/view/the-core-ios/9780133510119/graphics/06fig03.jpg)

**Comment by jcesarmobile** [comment]
The accessory bar is handled by the OS, we can't change it other than showing/hiding it.
