### ISSUE TITLE
Feat: support for on screen keyboard

### ISSUE THREAD

**Issue by loopezz** [ionic-team/cordova-plugin-ionic-keyboard#109]
It would be very nice to have a fully working on screen keyboard (virtual) in a web browser / Electron build.

Use case:
A computer with an Ionic app running in kiosk mode with a touch screen.

**Comment by jcesarmobile** [comment]
This plugin doesn't target browser nor electron.

And touch screen devices already have virtual keyboards, so I don't think that belongs to this plugin.
