### ISSUE TITLE
keyboard submit button difference iOS and Android

### ISSUE THREAD

**Issue by TheDuc** [ionic-team/cordova-plugin-ionic-keyboard#11]
In Android the 'submit' button in the lower right selects the next input field, and submits the form after the last field. In iOS however, the 'return' button always submits the form directly, even when there are next input fields not yet filled in.
Is there a way to change the behaviour of the return button in iOS to behave like the one in Android?

**Comment by mlynch** [comment]
Not that I know of, sorry
