### ISSUE TITLE
Different JS methods interface. Keyboard.close <-> Keyboard.hide

### ISSUE THREAD

**Issue by danicastanos** [ionic-team/cordova-plugin-ionic-keyboard#12]
The JS methods interface is not consistent as the methods to close the keyboard in Android and iOS are different.

For Android is close, meanwhile for iOS is hide.

**Comment by noxiousmobile** [comment]
Yes it's a total mess

**Comment by jacquesdev** [comment]
I believe this PR https://github.com/ionic-team/cordova-plugin-ionic-keyboard/pull/5 (now merged) fixes that issue, so you can close this issue.

**Comment by mlynch** [comment]
Should be fixed in 2.1.2 that was just published
