### ISSUE TITLE
setResizeMode not working after last update

### ISSUE THREAD

**Issue by vadimwe** [ionic-team/cordova-plugin-ionic-keyboard#124]
Compile error:

> error TS2345: Argument of type '"native"' is not assignable to parameter of type 'KeyboardResizeMode'.
> [ng] 50     this.keyboard.setResizeMode('native');

Version 5.15.0
Angular 8.2.9

**Comment by RaccoonFive** [comment]
Changing it in the config.xml also doesn't seem to work anymore...

**Comment by yyesi** [comment]
```
import { Keyboard, KeyboardResizeMode } from '@ionic-native/keyboard/ngx';

constructor(private keyboard: Keyboard ) {
    this.keyboard.setResizeMode(KeyboardResizeMode.Native);
}
```

**Comment by jcesarmobile** [comment]
The types are not bundled with the plugin, so it's not really a plugin issue. 
But you have to use it as yyesi explained.
