### ISSUE TITLE
keyboardDidShow event fired 3 times for third party keyboard

### ISSUE THREAD

**Issue by Mavlarn** [ionic-team/cordova-plugin-ionic-keyboard#13]
I had a third party keyboard, when the keyboard is shown, the keyboardDidShow is fired 3 time.

And, the original keyboard height is 216, third party keyboard height is 282. The fired event is : 

fired ev.keyboardHeight is 282
fired ev.keyboardHeight is 216
fired ev.keyboardHeight is 282

and， In the screen, the height is used as 216, which is a little short, so the input field is not shown.

**Comment by Mavlarn** [comment]
sogou on iOS.

**Comment by jcesarmobile** [comment]
Sorry, but we can't fix this, it's probably the third party keyboard's fault. The plugin just converts the native event to a js event, but if that keyboard sends 3 events, the plugin will retransmit those 3 events.

As far as I remember, there was a way of not allowing 3rd party keyboards, so if you don't want users to use that or other keyboards you can look into that.
