### ISSUE TITLE
Support for '@ionic-native/keyboard'

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/cordova-plugin-ionic-keyboard#14]
Is the the plugin for the wrapper of '@ionic-native/keyboard'? 

Or does it only work with the deprecated repo https://github.com/ionic-team/ionic-plugin-keyboard as it points to in the doc: https://ionicframework.com/docs/native/keyboard/

If that's true - why wouldn't the plugin wrapper point to the latest/supported cordova plugin?

**Comment by MichelKansou** [comment]
Having the same issue here why is the main repo is deprecated and `@ionic-native/keyboard` is not supported ?

**Comment by jaybloke** [comment]
This is the deal dealbreaker for me... I reverted back to the deprecated keyboard as this is so poorly documented it's almost unbelievable.

**Comment by jacquesdev** [comment]
@mlynch

**Comment by mlynch** [comment]
Duplicate of #9
