### ISSUE TITLE
What is happening on this repo?

### ISSUE THREAD

**Issue by devotoare** [ionic-team/cordova-plugin-ionic-keyboard#18]
Seriously. Months of no replies. How the heck are we supposed to be properly using keyboard methods and stuff?

**Comment by dimitrivalax** [comment]
hello @devotoare 

i think the readme file is out to date !!!

to close the keyboard i use "window.Keyboard.close(); " instead of "window.Keyboard.hide();"

and instead of "hideFormAccessoryBar" i use "hideKeyboardAccessoryBar".

Hope this helps.

**Comment by devotoare** [comment]
The docs are still useless. There is no information on running npm install, how to import, etc. There's note even an export in the code so this can't be used properly. All we really need is a working Ionic 3 example. Because right now there isn't one.

In addition this is an Ionic plugin, it says so in the name. So having differences between the function names to achieve the same task is ... poor. At best. That should be handled by the plugin itself.
