### ISSUE TITLE
How I can use this plugin with capacitor?

### ISSUE THREAD

**Issue by ttibau** [ionic-team/cordova-plugin-ionic-keyboard#23]
I've installed this plugin with capacitor and I need to use the **Preferences** KeyboardResize and KeyboardResizeMode, but in capacitor I don't find the config.xml. 
How I can use this plugin with capacitor?
Because when I click on input, all of the content is pulled up.
Thanks!

**Comment by mlynch** [comment]
This plugin isn't for Capacitor. Capacitor has its own

**Comment by ttibau** [comment]
I got it, but capacitor's plugin do not have KeyboardResize configuration. 
Thanks
