### ISSUE TITLE
disableScrollingInShrinkView not working?

### ISSUE THREAD

**Issue by trinitiwowka** [ionic-team/cordova-plugin-ionic-keyboard#24]
on platform Android keyboard overflow view.

WEB: http://joxi.ru/a2XnYXgU10gP3r
Android: http://joxi.ru/1A5GJo0Un0JMZm

**Comment by mlynch** [comment]
Can you describe the issue more? Not sure what to look at. Thanks

**Comment by jcesarmobile** [comment]
closing as there was no answer and it's not clear what the issue is.
