### ISSUE TITLE
Open / Close Methods

### ISSUE THREAD

**Issue by jeffreyramia** [ionic-team/cordova-plugin-ionic-keyboard#26]
Both methods .show() and .hide() do not work and have no effect whatsoever.

**Comment by ronnyroeller** [comment]
Same problem with iPhone XS / iOS 12.0

**Comment by jcesarmobile** [comment]
show() is not supported on iOS (not technically possible), use the .focus() method of the input where you want to type.
hide() is working fine with latest version.
