### ISSUE TITLE
View resize wrong height when opening HTML5 Date input keyboard. 

### ISSUE THREAD

**Issue by oleksiy-nesterov** [ionic-team/cordova-plugin-ionic-keyboard#28]
related to this https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/16

I see the same issue on iPhoneX

`<preference name="KeyboardResize" value="false" />`
`<preference name="KeyboardResizeMode" value="native" />`

[screen](https://api.monosnap.com/rpc/file/download?id=KQ5DTQGU2cOhr8jNlSmLUImmQ4O1fK)
![](https://api.monosnap.com/rpc/file/download?id=KQ5DTQGU2cOhr8jNlSmLUImmQ4O1fK)

**Comment by oleksiy-nesterov** [comment]
same issue for old plugin "ionic-plugin-keyboard"

**Comment by oleksiy-nesterov** [comment]
for iPhone 7+, looks better, but the issue still present. The date chooser overlaps keyboard bar.

**Comment by jcesarmobile** [comment]
I can no longer reproduce on iOS 12.4.

Also we don't really act on how the date picker is displayed, this seems like it was an Apple bug.
