### ISSUE TITLE
Set dark keyboard style

### ISSUE THREAD

**Issue by ccorcos** [ionic-team/cordova-plugin-ionic-keyboard#34]
Would be nice with iOS dark mode coming out :)

**Comment by jcesarmobile** [comment]
It has been implemented in the own cordova-plugin-ionic-webview, so not sure if it's worth duplicating it here.

**Comment by ccorcos** [comment]
Ah yes. Right here: https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/44

Thanks for the heads up!

**Comment by loama** [comment]
Is there some way to change it automatically? Like show the light keyboard when the user has that theme selected in the phone?
