### ISSUE TITLE
Keyboard height is 48px too short on Samsung s8

### ISSUE THREAD

**Issue by remcoanker** [ionic-team/cordova-plugin-ionic-keyboard#36]
On a Samsung S8 with Android 8 (and presumably more Samsung devices) the keyboard height is 48px too short.

It does give the correct height when I remove the fix for Android 21+, but then it gives a too large height on different devices (Nexus 5x).

Is there a different way to calculate the keyboard height?

This is with `KeyboardResize false`

Edit: It looks like its the bottom bar thats hidden normally, but shown when the keyboard is open. On Samsung S8, you can toggle the bottom bar visibility by double tapping the dot on the left. This plugin gives the wrong height when it's set to hidden.

**Comment by ttthub** [comment]
+1 
any ideas to work around this please?

**Comment by jcesarmobile** [comment]
Closing in favor of https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/90 as it covers more devices and not just Samsung ones.
