### ISSUE TITLE
disableScroll method disappear

### ISSUE THREAD

**Issue by Makeon** [ionic-team/cordova-plugin-ionic-keyboard#42]
disableScroll() method disappear in 4.15.0 version
what method one need use now?

**Comment by NMastracchio** [comment]
This boggles my mind. Amidst the sea of seemingly infinite Stack and Ionic forum posts about scrolling/keyboard issues, using the disableScroll method is the most common solution. And yet, they removed it from the currently supported plugin.

**Comment by mlynch** [comment]
Version 4.15.0 of what? The current keyboard plugin version is 2.1.3

**Comment by togro** [comment]
> disableScroll() method disappear in 4.15.0 version
> what method one need use now?

On 4.15.0 disappear, I donwgrade version with

 npm install --save @ionic-native/keyboard@4.12.0 and works again

**Comment by Makeon** [comment]
> Version 4.15.0 of what? The current keyboard plugin version is 2.1.3
Version 4.15.0 of @ionic-native/keyboard
I downgrade to 4.13.0 and it works
But I'd like to use the latest version, it has useful methods and I need disableScroll()
How I can replace disableScroll() in 4.15.0?

**Comment by Xample** [comment]
I am also looking for an alternative. I do now have a glitch when arriving on a page with autofocus (the keyboard opens, covers half of the page and the header is hidden)

**Comment by abhijithp** [comment]
+1

**Comment by mlynch** [comment]
@manucorporat I see `disableScroll` is in our older deprecated plugin but not this one. Maybe just an oversight? https://github.com/ionic-team/ionic-plugin-keyboard/blob/master/src/ios/IonicKeyboard.m

Thoughts on adding that back in?

**Comment by lokkeshjaya** [comment]
+1

**Comment by collindutter** [comment]
I was able to fix my keyboard resizing issues with this config preference:
`<preference name="KeyboardResize" value="false" />`

Sorry if this is obvious, but somehow I missed this option after hours of searching!

**Comment by Xample** [comment]
@collindutter it worth giving a try, perhaps I can do the same. I just need to make sure it will work across the whole app

**Comment by hardcorelite** [comment]
@Xample @mlynch Found a solution?

**Comment by tribalboy3000** [comment]
<preference name="KeyboardResize" value="false" />

Does not work

**Comment by hardcorelite** [comment]
npm install --save @ionic-native/keyboard@4.12.0 

GOOOOOOOD

**Comment by tribalboy3000** [comment]
This still didn't work for me.
'cordova plugin list'  shows: cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
package.json dependencies show: 
"@ionic-native/keyboard": "^4.12.0",
"cordova-plugin-ionic-keyboard": "2.1.3",

Then in deviceready I tried:
Keyboard.disableScroll(true); & cordova.plugins.Keyboard.disableScroll(true);

But when I focus on an input it still scrolls. Am I missing something?

**Comment by heidji** [comment]
maybe something you missed in the config.xml but this isn't the issue to discuss it at. this bug merely talks about a missing function..

**Comment by uviekelvin** [comment]
This issue is really frustrating. hoping this get resolves by the ionic team

**Comment by JrSagas** [comment]
> This still didn't work for me.
> 'cordova plugin list' shows: cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
> package.json dependencies show:
> "@ionic-native/keyboard": "^4.12.0",
> "cordova-plugin-ionic-keyboard": "2.1.3",
> 
> Then in deviceready I tried:
> Keyboard.disableScroll(true); & cordova.plugins.Keyboard.disableScroll(true);
> 
> But when I focus on an input it still scrolls. Am I missing something?

Hi, did you get a solution?
I have the same issue

**Comment by tmk1991** [comment]
@mlynch  everyone is referring to the @ionic/native wrapper for the keyboard. There was an issue where the wrapper wasn't using this cordova plugin before. See @mhartington 's response: https://github.com/ionic-team/ionic-native/issues/2306#issuecomment-392768387
 
https://github.com/ionic-team/ionic-native/issues/2743

on the version 4.15.0 of the native wrapper this was corrected but now this cordova plugin doesn't have the disableScroll functionality. https://github.com/ionic-team/ionic-native/blob/master/CHANGELOG.md

**Comment by floriandorre** [comment]
Any news about this issue ?

**Comment by akildemir** [comment]
> I was able to fix my keyboard resizing issues with this config preference:
> `<preference name="KeyboardResize" value="false" />`
> 
> Sorry if this is obvious, but somehow I missed this option after hours of searching!

This doesn't work in my case.

**Comment by hardcorelite** [comment]
npm install --save @ionic-native/keyboard@4.12.0

🤦🏻‍♀️

**Comment by heikomat** [comment]
I had a problem where the app would automatically scroll to the focused element whenever an element got focused, and there seemed to be no way to prevent this.

Downgrading `@ionic-native/keyboard` was not an option, because of incompatible rxjs versions.

As it turns out, **There is an undocumented (private) configration** for the IonicModule called [`scrollAssist`](https://github.com/ionic-team/ionic/blob/39fbc323480207417b41ff20d22badd91798ee2d/core/src/utils/config.ts#L173), wich is true by default, but can just be disabled like this in your _app.module.ts_:

```typescript
    IonicModule.forRoot({scrollAssist: false}),
```

Disabling scrollassist made the app no longer auto-scroll to focused elements on iOS.
See [this SO-answer](https://stackoverflow.com/a/41163695) for some more context.

**Comment by Heliks** [comment]
You remove functionality that is crucial for some iOS workarounds and then don't even bother to address this issue in almost 9 months? Is this a joke?

**Comment by nawwa** [comment]
Any progress ? Still an issue ..

**Comment by desmondcain** [comment]
To fix this for me, the problem was that I had to switch from UIWebView to WKWebView and use cordova-plugin-ionic-keyboard. As noted here: https://github.com/ionic-team/cordova-plugin-ionic-keyboard#cordova-plugin-ionic-keyboard cordova keyboard is meant to work with WKWebView. I stumbled on this after digging around and landing on Max's comment: https://github.com/ionic-team/ionic-plugin-keyboard/issues/305#issuecomment-377813835

**Comment by mlynch** [comment]
@Heliks hid your comment as it's abusive and unproductive. Watch your behavior.

We're going to be adding this feature back into either the keyboard plugin or the webview plugin and will provide an update once that is ready.

**Comment by heidji** [comment]
why is this discussion even happening here? isn't the problem about the ionic-native wrapper or am i missing something?

**Comment by jcesarmobile** [comment]
@heidji the ionic wrapper was using the old keyboard plugin, which is deprecated. The wrapper now uses this plugin, which doesn't have disableScroll method and people is complaining about it.

**Comment by heidji** [comment]
@jcesarmobile oh i see it now, it just displays a warning that it was removed :D, sorry I misread the function
