### ISSUE TITLE
No numeric keyboard type with decimal point.

### ISSUE THREAD

**Issue by litianyangz** [ionic-team/cordova-plugin-ionic-keyboard#43]
<ion-item>
       <ion-input type="number" pattern="\d*" value="" placeholder="1234"></ion-input>
</ion-item>

There is no decimal point.

**Comment by terminaltor** [comment]
+1

**Comment by rondog** [comment]
this would be a great addition. Really need this for calculations.

**Comment by jcesarmobile** [comment]
The plugin just helps managing the keyboard, but doesn't create new keyboard types, so adding a decimal point is not something we can do.

**Comment by midhunadarvin** [comment]
Hi, Can you reopen this issue? I know this team isn't creating new keyboard types, but the decimal pad is a native keyboard type in iOS. But with `<input type="number" />` it doesn't work.

Similar issues in other repos :
https://github.com/ionic-team/ionic-plugin-keyboard/issues/191
