### ISSUE TITLE
Add "setResizeMode" method description to the README.md

### ISSUE THREAD

**Issue by stas-dolgachov** [ionic-team/cordova-plugin-ionic-keyboard#44]
Hey guys,
Thank you all for this awesome plugin, I appreciate what you all are doing.

**Description:**
Previously in https://github.com/ionic-team/cordova-plugin-ionic-keyboard/pull/39
the new "setResizeMode" method was added.
Could we add this method description to the README.md?

If you don't mind, **I will create a pull request for that**, thank you!

**Comment by jcesarmobile** [comment]
Merged, thanks!
