### ISSUE TITLE
ionic4 install @ionic-native/keyboard is error

### ISSUE THREAD

**Issue by lwh2015** [ionic-team/cordova-plugin-ionic-keyboard#49]
[ng] ERROR in node_modules/@ionic-native/keyboard/index.d.ts(2,10): error TS2305: Module '"E:/myWork/myBlogApp/node_modules/rxjs/Observable"' has no exported member 'Observable'.
[ng] node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Comment by collindutter** [comment]
For all native plugins on Ionic 4 you need to install the beta version.
`npm i @ionic-native/keyboard@beta`
Then, when importing the provider in your app.module, import it from the ngx folder like so:
`import { Keyboard } from '@ionic-native/keyboard/ngx';`

Hope this helps!

**Comment by lwh2015** [comment]
> For all native plugins on Ionic 4 you need to install the beta version.
> `npm i @ionic-native/keyboard@beta`
> Then, when importing the provider in your app.module, import it from the ngx folder like so:
> `import { Keyboard } from '@ionic-native/keyboard/ngx';`
> 
> Hope this helps!

OK,Thanks

**Comment by almeidacavalcante** [comment]
> For all native plugins on Ionic 4 you need to install the beta version.
> `npm i @ionic-native/keyboard@beta`
> Then, when importing the provider in your app.module, import it from the ngx folder like so:
> `import { Keyboard } from '@ionic-native/keyboard/ngx';`
> 
> Hope this helps!

Works pretty fine now, Thank you

**Comment by jcesarmobile** [comment]
closing as it was fixed by updating @ionic-native/keyboard
