### ISSUE TITLE
the keyboard hide the input inside the form

### ISSUE THREAD

**Issue by dimalahbal** [ionic-team/cordova-plugin-ionic-keyboard#57]
i have  a problem with the keyboard , it hide the lowers inputs inside a form 

any help please ?

**Comment by geltoncruz** [comment]
I had the problem but I solved it.
The position attribute, in ion-col, has the relative value as the default.
So I changed the attribute position value to "initial"

```css
ion-col {
position: initial
}
```

**Comment by jcesarmobile** [comment]
Can you provide a sample app or at least some code and the preferences you are using for the resize mode?

**Comment by geltoncruz** [comment]
> Can you provide a sample app or at least some code and the preferences you are using for the resize mode?

Yes! I can!

I posted the page and scss on github gist.
you can see in: 
[https://gist.github.com/geltoncruz/c6cc8487a9ef8364d6a0386824c43a9d](url)

**Comment by jcesarmobile** [comment]
I was asking to the OP, not to you @geltoncruz, you said you had solved it.
Also, I was asking about his plugin preferences too, not just code.

Going to close as he didn't answer, but I hope your code helps others.
