### ISSUE TITLE
WARN: Native: tried calling Keyboard.hideKeyboardAccessoryBar, but the Keyboard plugin is not installed.

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/cordova-plugin-ionic-keyboard#6]
Hi, I get the following (webview and keyboard related) messages in my XCode log:

```
CDVWKWebViewEngine: trying to inject XHR polyfill
CDVWKWebViewEngine will reload WKWebView if required on resume
Using Ionic WKWebView
CDVIonicKeyboard: resize mode 1
[CDVTimer][keyboard] 13.301969ms
WARN: Native: tried calling Keyboard.hideKeyboardAccessoryBar, but the Keyboard plugin is not installed.
WARN: Install the Keyboard plugin: 'ionic cordova plugin add ionic-plugin-keyboard'
```

Checking the source code, I found out that the method is actually called `hideFormAccessoryBar` on iOS, doesn't work when trying to set it to `false`, and the whole plugin is just kind of a mess, and pull requests are being more or less ignored.

Please have a look at this. And consider adding an option to resize only the tab page content (so the tab bar doesn't show up on top of the keyboard). Until then I'll just remove this plugin.

**Comment by noxiousmobile** [comment]
Yes, actually this cordova plugin asks for 'hideFormAccessoryBar' but it does not look that its in synch with ionic native keyboard which does not recognize these. Actually needs  the right provider for it, to support all these new methods.

**Comment by diegodotta** [comment]
Super Cool! How can I use this 2.1.0 @mlynch ?
I tried "plugin add ..@2.10" without success! :(
