### ISSUE TITLE
iOS keyboard breaks all position:fixed elements

### ISSUE THREAD

**Issue by imizaac** [ionic-team/cordova-plugin-ionic-keyboard#65]
Upon opening keyboard all position fixed elements become position:absolute and remain in their pre opening keyboard position.

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
What are your keyboard settings? (preferences in config.xml)

**Comment by jcesarmobile** [comment]
I can't reproduce. The default settings resize the webview, so might look like the elements are moved, but the reality is they webview was resized. If you don't want that behaviour set the `KeyboardResize` preference to false `<preference name="KeyboardResize" value="false" />`.

If already using that preference and you can still reproduce, feel free to reopen, but please, provide some code and screenshots or a sample project.

**Comment by elvisgraho** [comment]
+1. Issue seems that when you have fixed element (such as footer) and you have a searchbox (that can push fixed element with the keyboard).

```<preference name="KeyboardResize" value="false" />``` does not fix the issue.
