### ISSUE TITLE
Not resizing at all in ionic V1

### ISSUE THREAD

**Issue by geshub** [ionic-team/cordova-plugin-ionic-keyboard#7]
Upgraded from ionic-plugin-keyboard to cordova-plugin-ionic-keyboard for my ionic V1 app and resizing is not working anymore (on IOS with WKWebView)
I've got this in config.xml 

   <preference name="KeyboardResize" value="true" />
    <preference name="KeyboardResizeMode" value="native" />

Also the events are not fired.
It's working normally with cordova-plugin-keyboard.

Is there any other steps to install it for V1 ?

**Comment by mlynch** [comment]
Should be fixed in 2.1.2 that was just published
