### ISSUE TITLE
Locale accessory bar 

### ISSUE THREAD

**Issue by miroshnichenkoYaroslav** [ionic-team/cordova-plugin-ionic-keyboard#75]
Can I place my value instead of a button "Done"? Depending on the system language

**Comment by jcesarmobile** [comment]
It's translated automatically if your project support different languages.

If you want to support multiple languages you have to add the `CFBundleLocalizations` key with an array of supported languages in the Info.plist file, you can do it manually or using `edit-config` or `config-file` tags in `config.xml` like this:

```
<config-file parent="CFBundleLocalizations" target="*-Info.plist">
    <array>
        <string>en</string>
        <string>es</string>
    </array>
</config-file>
```
