### ISSUE TITLE
How to stop the ion-footer to move over the keyboard

### ISSUE THREAD

**Issue by ios-dev-newbie** [ionic-team/cordova-plugin-ionic-keyboard#77]
I am having a simple view. I have a title in nav bar and below it there is a search bar when user will click on search bar the keyboard comes up.

I have a button in my <ion-footer>. But when I clicked on search bar it moved my footer content over the keyboard. How I can stop that ?

Please find the sample gist on below Link:
https://gist.github.com/ios-dev-newbie/433bb867fd305983d34e72cb77690616

Please let me know what can be done?

Thanks in advance.

**Comment by khashashin** [comment]
Clarification, this only happens on Android.

**Comment by presidentnickson** [comment]
This is happening for me on iOS.

**Comment by hybridsimone** [comment]
Happens for me as well, but only on iOS. 
Any advice how to fix this?

**Comment by edgargrs** [comment]
try add `keyboard-attach` in your footer
`<ion-footer keyboard-attach>`

**Comment by ThonyFD** [comment]
@edgargrs  keyboard-attach is not longer supported!

**Comment by jcesarmobile** [comment]
I think that's how the ion-footer is supposed to work, if you don't want to show it, you can listen for the keyboard events and hide it when the keyboard is going to appear and show it again when the keyboard is going to disappear.

Another option is to change the keyboard resize options to not resize.

**Comment by ThonyFD** [comment]
@jcesarmobile Your first option generate visual lacks, because the keyboard observable is slow and css apply at impredecible moments.

And the second, change the behavior for all the app and in some cases it's needed the actual behavior.

In my opinion, the ion-footer need something like the old keyboard-attach directive

**Comment by jcesarmobile** [comment]
Anyway, not a bug on the plugin, create a feature request on ionic repository if you want that feature added on ion-footer
