### ISSUE TITLE
Is it possible to preventDefault within the keyboardWillShow event

### ISSUE THREAD

**Issue by john-doherty** [ionic-team/cordova-plugin-ionic-keyboard#78]
Is there a way to cancel the keyboardWillShow event to stop the keyboard from showing in certain conditions?

```js
window.addEventListener('keyboardWillShow', (event) => {
    if (document.activeElement && document.activeElement.id === 'whateverEl') {
        return false;
    }
});
```

**Comment by jcesarmobile** [comment]
No, it's not possible.
What you can do is set the field to readonly="true", so it still sends the click event but prevents from writing, or trigger blur on the field or calling hide (but it might still show the keyboard for a brief moment)
