### ISSUE TITLE
How to hide keyboard on input focus?

### ISSUE THREAD

**Issue by templatetuners** [ionic-team/cordova-plugin-ionic-keyboard#80]
I have an input and I need to focus it to populate with data from a bluetooth barcode scanner.
On `input:focus()` the keyboard is always opening.
Tried with `Keyboard.hide();` with `setTimeout` nothing works.

**Comment by jcesarmobile** [comment]
iOS? Android? both?

Are you using cordova-plugin-ionic-webview?

**Comment by templatetuners** [comment]
Android Cordova and not using ionic-webview

**Comment by OMGFoxChen** [comment]
Have you solved it? I have the same problem as you

**Comment by OMGFoxChen** [comment]
@templatetuners I solved this by setting "readonly".

`<ion-input  (focus)="handleScanInputFocus()" #scanInput id="scan_input" ></ion-input>`

`@ViewChild('scanInput') scanInputElement: any;`

handleScanInputFocus(){
    let elm = this.scanInputElement.getElementRef().nativeElement.firstElementChild;

    elm.setAttribute('readonly','readonly'); //The keyboard will not pop up
    setTimeout(() => {
      elm.removeAttribute('readonly');  //Remove the "readonly", and the cursor is still in
    }, 200)
  }

**Comment by jcesarmobile** [comment]
The keyboard will always appear when you focus it, for preventing it you can do some approaches as the suggested by @OMGFoxChen.

**Comment by jaronavales** [comment]
How about you have some activity with the page like gestures tap swipe pan, is the cursor still in? @OMGFoxChen

**Comment by jaronavales** [comment]
@OMGFoxChen you save me <3 Thank you!

**Comment by DmitryBara** [comment]
You could use `inputRef.setBlur()` immediately after you focused `<IonInput>`
Then: 1) keyboard will not be appear, 2) input will not be focused 3) but content will be scrolled to that input
