### ISSUE TITLE
Defaulting to numeric / punctuation keyboard with input type text

### ISSUE THREAD

**Issue by daviddickson** [ionic-team/cordova-plugin-ionic-keyboard#83]
I have the same use case mentioned here:
https://stackoverflow.com/questions/30599596/how-to-start-in-numeric-side-of-keypad-in-objective-c and I want to implement the answer in a fork of this repo but am unsure of how exactly to add the code to implement the answer in this codebase.  Anyone have suggestions?

**Comment by jcesarmobile** [comment]
That can't be done on the webview, the answers refer to native fields.

You could create a plugin that when you focus on a html input field shows a native input field over it with that type set, but will probably be hacky.
