### ISSUE TITLE
Be able to set KeyboardResize programatically

### ISSUE THREAD

**Issue by jpike88** [ionic-team/cordova-plugin-ionic-keyboard#88]

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/cordova-plugin-ionic-keyboard#keyboardsetresizemode-for-ios-only

**Comment by jpike88** [comment]
No, I'm talking about this, please reopen:

This can only be set in config.xml, should be available to tweak programatically.

`<preference name="KeyboardResize" value="true" />`

**Comment by jcesarmobile** [comment]
If KeyboardResize is set to false on init, that set the resize mode to none, if set to true then it can be one of the other 3 resize modes.
With the function to change the mode programmatically you can set the resize mode to any of the 4 resize modes, ionic, body, native or none, so setting to ionic, body or native are like setting KeyboardResize to true and none to false.

**Comment by jpike88** [comment]
Having KeyboardResize and KeyboardResizeMode as options in config.xml is confusing, they seem to affect the same option. Doesn't make any sense..
