### ISSUE TITLE
Update @ionic-native/keyboard to this plugin

### ISSUE THREAD

**Issue by noxiousmobile** [ionic-team/cordova-plugin-ionic-keyboard#9]
All of the new methods are not recognized, such as **hideFormAccessoryBar**.
ionic-native/keyboard looks like its still using the old methods so it really does not play well alongside with this new cordova plugin together. At official ionic docs site, there are still the old methods

>  https://ionicframework.com/docs/native/keyboard/

I do understand (and see by commits) that this will be more monitored plugin, but at this stage there are issues that needs to be addressed.

**Comment by Tronix117** [comment]
That is critical...

**Comment by TheDuc** [comment]
This issue is also opened at the ionic-native repo.
See https://github.com/ionic-team/ionic-native/issues/2306 for a possible workaround.

**Comment by noxiousmobile** [comment]
I don't have the **prediction bar** showing on iOS 11.3 for the keyboard. I don't know is it because of the iOS version or its related to the plugin.

**Comment by noxiousmobile** [comment]
I won't go for any workaround for now as it's really not secure and safe way to go.

**Comment by ghenry22** [comment]
@mhartington it's been a couple of months and I just hit this problem upon updating the keyboard plugin, any chance that ionic-native could get updated to resolve this?

**Comment by iaguilera14** [comment]
Same here. Had to bypass the standard way of doing it because @ionic-native doesn't work.

**Comment by yannbf** [comment]
@iaguilera14 what was your approach?

**Comment by jcesarmobile** [comment]
ionic-native/keyboard now uses this plugin, closing 

https://github.com/ionic-team/ionic-native/pull/2743

**Comment by HanojHanu** [comment]
> package.json
>     "@ionic-native/keyboard": "^4.20.0",

**but cordoava plugin is **

>     "cordova-plugin-ionic-keyboard": "2.1.3",


**not able update my plugin why**
