### ISSUE TITLE
disappearing keboard when input typing

### ISSUE THREAD

**Issue by asterism612** [ionic-team/cordova-plugin-ionic-keyboard#92]
The keyboard keeps disappearing when I focus on the input and typing.
in Themeable inapp Browser.

How to solve?

Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 19 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.11.0 (/usr/local/Cellar/node/10.11.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by jcesarmobile** [comment]
keyboard plugin only has effect on the WKWebView, not in the themabe inappbrowser, you should report the problem in that plugin repo.
