### ISSUE TITLE
Turn off keyboard

### ISSUE THREAD

**Issue by monove** [ionic-team/cordova-plugin-ionic-keyboard#94]
I am looking for the ability to force the keyboard to stay hidden without any hacks.

I've tried doing a hide() on keyboardWillShow but that shows the keyboard then quickly hides it which is terrible UX.

The input device for this field is a magstripe reader so showing keyboard is not ok.

Any ideas?

**Comment by jcesarmobile** [comment]
No, it's not possible.

There are some workarounds, like the explained on https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/80
