### ISSUE TITLE
It might be right to warn when the old plugin is installed alongside this one

### ISSUE THREAD

**Issue by Hissvard** [ionic-team/cordova-plugin-ionic-keyboard#97]
I recently had an issue caused by the fact that I removed the the now deprecated `ionic-plugin-keyboard` and installed this one instead.
Pulling from another machine, the older plugin somehow got readded alongside this one by phonegap - causing stuff to stop working in mysterious ways: I could access window.Keyboard and call functions but they were simply discarded as "INVALID".

It might save people some confusion if we could detect the older plugin being installed alongside this one and warn the developer, unless there's a reason I'm forgetting for people to *want* to install both.

**Comment by jcesarmobile** [comment]
I've fixed the conflicts when the two plugins were installed, but won't warn if both are installed.
